### ISSUE TITLE
Generate real questions/answers scripts

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#18]
PP Session - 8hrs estimated

todos:
1. scan NS google drive for finance for docs like:
 - Already scanned https://docs.google.com/spreadsheets/d/1MYNg03Ulhqnr_4walJ5BNqwwn2bJwcXOcusmgGAh6sY/edit?pli=1#gid=0
 - Vacation payment : https://docs.google.com/a/nearsoft.com/document/d/1E7D6FXen876gXQwjSPOtE3FCBgK53xMo2CBb1CTA0eU/edit?usp=drive_web
 - Time Off procedure: https://docs.google.com/document/d/1JbMiYhO4W7eqolhdUqOAlRSgPEN3t7X3WsRweJOPE-w/edit
 - Declaración Anual como asalariados : https://docs.google.com/document/d/18hSZJJEN8Xws2ZQxNcLZOe0WwBw10xB7_u9ZboimgDI/edit#heading=h.1e26p8vo1fr5
2. generate scripts with at least 10 questions with their answers

**Comment by imarban** [comment]
I've added more questions on Flyway scripts. The database needs to be dropped and created for this changes being reflected.
