### ISSUE TITLE
High - Could not load [db/migration]

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#20]
**When it happens:**
At the moment of running mvn spring-boot:run - Server can not start because of this

**Error says:**
FlywayException: Unable to scan for SQL migrations in location: classpath:db/migration

**Failed tests:** 
  FileSystemStorageTest.replaceFile:37 expected:<false> but was:<true>
  FileSystemStorageTest.saveFile:30 expected:<false> but was:<true>
Tests in error: 
  QuestionsApplicationTests.contextLoads » IllegalState Failed to load Applicati...

**Caused by:**
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [db/migration]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1355)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:976)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1139)
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner.getLocationUrlsForPath(ClassPathScanner.java:190)
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner.findResourceNames(ClassPathScanner.java:148)
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner.scanForResources(ClassPathScanner.java:73)
	at org.flywaydb.core.internal.util.scanner.Scanner.scanForResources(Scanner.java:53)

**Comment by imarban** [comment]
Spring boot is able to run the migrations from classpath:db.migration but it only occurs if you run it as simple Java Application com.nearsoft.questions.config.QuestionsApplication#main and not using Maven to build it.

There are two choices: 
1. Run mvn compile before mvn spring-boot:run to compile the migrations files for flyway
2. Run NSQ as simple Java app changing the scope of spring-boot-starter-tomcat to compile instead provided.

**Comment by imarban** [comment]
Spring boot is able to run the migrations from classpath:db.migration but it only occurs if you run it as simple Java Application com.nearsoft.questions.config.QuestionsApplication#main and not using Maven to build it.

There are two choices: 
1. Run mvn compile before mvn spring-boot:run to compile the migrations files for flyway
2. Run NSQ as simple Java app changing the scope of spring-boot-starter-tomcat to compile instead provided.

**Comment by wdonet** [comment]
We are adding in the scripts sequences for each table and pointing to it at POJOs anotating at id like this:
   @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_seq")
    @SequenceGenerator(name = "user_seq", sequenceName = "user_seq")

User POJO/ user Table  is a special case due to restrictions in Postgress. We need to use schema too anotating at class level like this:
@Entity
@Table(name = "user", schema = "public")
public class User {
