### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#6]
PP Session - 8hrs estimated

Is there an easy common way to handle migrations automatically in the app?

Does import.sql at classpath does the job?

Is it better to use external libraries lik flyway?
http://flywaydb.org/

todo:
 - add flyway library
 - configure it
 - add needed scripts 
 - add a document to help devs how to use it (rules)

**Comment by imarban** [comment]
Actually, I am having some troubles with import.sql in classpath root, it is not used by Hibernate. 

Anyhow, I think is better to use Flyway to manage the migrations. I will check how to configure it.
