### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by imarban** [wdonet/nsquestions#7]
PP Session: 10 hrs estimated
Add login with Google integrating with Spring Security and Spring Social?

1. Restriction for nearsoft.com domain
2. Redirection from Google after login
3. [possible to do it] Make public only home and private the rest

**Comment by imarban** [comment]
I've added LoginController and /login path mapping to signup and signin with Google accounts. Still pending check domain of email for restrict authentication (@company.com)

**Comment by wdonet** [comment]
shouldn't we receive a user object with name inside (user.name) once the user is logged in? #19 is relying on that in order to use the logged in user to add new questions/answers.
Should I change something?

**Comment by imarban** [comment]
Can you elaborate more on this?

**Comment by imarban** [comment]
I created an Interceptor. It handles the ModelAndView created by the Spring MVC controllers and add the user logged in (in case there is one). Please note that this occurs once the controller has executed so we can not get the user logged in inside the controller. For that issue, please check http://docs.spring.io/spring-security/site/docs/3.2.9.RELEASE/apidocs/org/springframework/security/web/bind/annotation/AuthenticationPrincipal.html

We need to get the current user instead send the user in the form (this way the user can be modified)

**Comment by wdonet** [comment]
I think User obj should not be added to the spring model since it is a Hibernate obj.

**Comment by wdonet** [comment]
This is still not working, I don't see the user logged in the hidden fields when adding questions/answers

**Comment by imarban** [comment]
How can I reproduce this problem? I've checked it and it seems to work

**Comment by wdonet** [comment]
It is supposed that when the user is logged in, the question form at /ask is taken the info and set the email in a hidden field, if it doesn't exist, it will use the default value which is nsq@nearsoft.com

**Comment by imarban** [comment]
The object user in the Spring model is of type com.nearsoft.questions.domain.auth.UserDetails, to access a property please use the name of the property in the Java class. UserDetails has no "name" property. The first name has been added to Ask Question button to demonstrate how this works.
