### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by wdonet** [wdonet/nsquestions#9]
It would be good to use translations or messages based on locale.

**Tasks :**
 - Create configuration for messages
 - Add two initial message files: English (**en**) and Spanish (**es**)
 - Change static values on templates (*/src/main/resources/templates*)

**Comment by imarban** [comment]
What should be the convention to add new messages and avoid duplication?
Should exist only a file per language with all the messages across all the application?

**Comment by imarban** [comment]
The convention agreed is add a prefix per functionality or module in the application. For example the messages for the Profile domain object in the authentication module is: auth.profile

**Comment by imarban** [comment]
It would be good to add the Locale Interceptor to read a query string parameter to change the language.

**Comment by imarban** [comment]
I've added an interceptor to check lang parameter for all requests and change the app language. At this moment, **es** and **en** are valid values. For example http://localhost:8080/login?lang=es will show the app in spanish.

https://github.com/wdonet/nsquestions/commit/b5354182450a581109dfd6199d5ef2ae52db4032
